### PR TITLE
issue/3279 Fix for active item on reset

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes https://github.com/adaptlearning/adapt_framework/issues/3279

### Fixed
* Active item must match model when reset

### CODE REVIEW

**Review by deltanetdan — APPROVED** [review]
Fixes the issue for Lars, but still needs _isCorrectAnswerShown: false adding [here](https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/models/questionModel.js#L329) to fix the original issue.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by joe-allen-89** [comment]
As with the same fix for MCQ (https://github.com/adaptlearning/adapt-contrib-mcq/pull/173), this causes an issue on iOS devices by not allowing any option to be selected.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by deltanetdan — APPROVED** [review]

**Review by joe-allen-89 — APPROVED** [review]
Working as expected, tested with iOS and latest framework.

**Pull request merged**
