### PR TITLE
Add option specific feedback

### PR DESCRIPTION
**Pull request by dancgray**
@moloko are there any example changes you think would improve this?

### CODE REVIEW

**Comment by moloko** [comment]
I would just add something to the README saying that: like MCQ, this component supports option-specific feedback. To see how to set that up, please look at the example.json in contrib-mcq

**Comment by moloko** [comment]
and just remove the option-specific feedback from this example.json

I think that should be enough for someone to be able to work this out

**Comment by taylortom** [comment]
+1 with Matt's suggestion

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Pull request merged**
