### PR TITLE
bugfix/accessibility: ios fix for aria label

### PR DESCRIPTION
**Pull request by oliverfoster**

### CODE REVIEW

**Comment by dancgray** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by oliverfoster** [comment]
this isn't going to work properly. give me a second to amend, apologies. the graphic alt tag is quite important for this, so needs moving to the option label.

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
