### PR TITLE
enable randomisation (issue #83)

### PR DESCRIPTION
**Pull request by moloko**

### CODE REVIEW

**Comment by moloko** [comment]
N.B this relies on https://github.com/adaptlearning/adapt-contrib-mcq/pull/111

**Comment by hrajotia** [comment]
+1

**Comment by belal-almassri-spongeuk** [comment]
+1

**Comment by zenduo** [comment]
+1 should this be done as a release? As this is broken for anyone downloading the current framework.

**Comment by moloko** [comment]
@zenduo yes I will do so, I did post a message in https://gitter.im/adaptlearning/adapt_framework stating that I would do master branch separately once this was accepted.

**Comment by zenduo** [comment]
@moloko cool

**Comment by moloko** [comment]
@zenduo in retrospect, I probably should have done this against master first - then pulled the changes from master into develop. will remember for next time!

**Comment by moloko** [comment]
@zenduo see #85 for master PR

**Pull request merged**
