### PR TITLE
issue/145 Fixed missing readOnly warning

### LINKED ISSUE #145: React error with onClick
image

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #145 

### Fixed
* Added readOnly property

### CODE REVIEW

**Comment by cahirodoherty-learningpool** [comment]
Is this the correct approach? I would have thought the defaultChecked React attribute is that we want to be setting in our template

**Comment by oliverfoster** [comment]
`onChange={onItemSelect}` and `checked={_isActive}` 
* Works on desktop until the model is reset on multiple attempts, then the state of the model and the state of the DOM go out of sync. 
* Doesn't seem to work on mobile.

`onClick={onItemSelect}` and `checked={_isActive}` 
* Works on mobile and desktop.
* React complains about `checked={_isActive}` without `onChange` or `readOnly`.

`onChange={onItemSelect}` and `defaultChecked={_isActive}`
* Works on mobile
* Resets fine.
* React doesn't complain.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

**Review by joe-allen-89 — COMMENTED** [review]
@oliverfoster should onClick on line 74 be onChange?

**Comment by oliverfoster** [comment]
Thanks Joe.

**Review by joe-allen-89 — APPROVED** [review]

**Pull request merged**
