### PR TITLE
Enhancement   variable column layout

### PR DESCRIPTION
**Pull request by guywillis**
Added a '_columns' attribute to GMCQ component JSON which allows users to set a column width per component. The JS automatically works out the % for each item and centrally aligns any spillover items.

eg; 5 items in a 3 column layout would have each item set to 33.3% with the second two items dropping to a new line and being centrally aligned.

Amended version number, readMe, example JSON, and schema. Plus removed redundant code.

### CODE REVIEW

**Comment by moloko** [comment]
did you mean to remove `_canShowModelAnswer` from example.json?

**Comment by guywillis** [comment]
I did not, added back in

**Comment by moloko** [comment]
Using the out-of-the-box course, if I set the `_columns` property of c-65 to `2` then I only get 2 options displaying in FF and Chrome.
In IE9 I get this:
2016-02-16 15_23_45-adapt version 2 0 demonstration _ question components

**Comment by guywillis** [comment]
Seems there's a bug when there's one more item than column e.g; 2 columns 3 items, 3 columns 4 items.

Will investigate and produce a fix

**Comment by guywillis** [comment]
Will create another branch and PR to these issues.

**Pull request closed without merging**
