### PR TITLE
Test folder has been removed.

### PR DESCRIPTION
**Pull request by belal-almassri-spongeuk**

### CODE REVIEW

**Comment by moloko** [comment]
Travis CI build is failing, I suspect because you haven't removed karma.conf.js

I see some of the repos have also had .bowerrc removed, not sure if that's correct or not. Trying to find out. It's nothing to do with removing the tests from the plugin though I'm sure.

**Comment by hrajotia** [comment]
To remove test packages -
- remove ```tests``` folder
- remove ```karma.conf.js``` file
- remove below lines from package.json
  * https://github.com/adaptlearning/adapt-contrib-gmcq/blob/develop/package.json#L7
  * https://github.com/adaptlearning/adapt-contrib-gmcq/blob/develop/package.json#L19-L21

**Comment by hrajotia** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
