### PR TITLE
explicitly specifying to use 'gmcq.hbs'

### LINKED ISSUE #86: 'mcq.hbs' is rendering insteed of 'gmcq.hbs'
this might have occurred after merging following PR https://github.com/adaptlearning/adapt_framework/pull/728

### PR DESCRIPTION
**Pull request by hrajotia**
Fixes #86

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by taylortom** [comment]
+1, can we add issues to JIRA though, rather than here.

**Comment by brian-learningpool** [comment]
+1

**Comment by hrajotia** [comment]
JIRA Ticket - https://adaptlearning.atlassian.net/browse/ABU-1070

**Pull request merged**
